### ISSUE TITLE
[FEATURE] Please update the plugin icon for NewUI compatibility

### ISSUE THREAD

**Issue by nadia-tarashkevich** [DataDog/datadog-for-intellij-platform#12]
Please update the plugin icon for consistency with NewUI

**What steps will reproduce the issue?**

- Set macOs to light mode
- Set intelliJ to a dark theme (like Dark)
- Open the menu View | Tool Windows, notice some icons look different. In the case at hand Datadog and Notifications
- What is the expected result?

**What happens instead?**
The icon in the menu is the same as for the toolwindow, i.e. the menu shows the dark variant of the icon, instead of the light variant (since on macOs the menu follows the OS setting)
This makes the icons barely visible.

![image](https://github.com/DataDog/datadog-for-intellij-platform/assets/96170885/cd24184c-3752-4db3-828a-47159c495c5d)

**Comment by abrooksv** [comment]
Hi @nadia-tarashkevich, sorry for the confusion. Brice who reported the ticket on youtrack (https://youtrack.jetbrains.com/issue/IDEA-322686) works for Datadog

We are trying to support the new UI but having issues with 2023.2 EAP

We are using the new `com.intellij.iconMapper` extension point and the config file:
```
{
  "icons": {
    "expui": {
      "toolwindows": {
        "datadog-newui.svg": "icons/toolwindows/datadog.svg",
        "datadog-newui_dark.svg": "icons/toolwindows/datadog_dark.svg"
      }
    }
  }
}
```

Everything appears correct in the IDE itself except for the icon in the indicated icon in the menu.

**Comment by bric3** [comment]
Done
