### ISSUE TITLE
[FEATURE] Pycharm support

### ISSUE THREAD

**Issue by pvicente** [DataDog/datadog-for-intellij-platform#16]

**Comment by jfree** [comment]
Thanks for your interest, this is on our roadmap for this quarter: https://github.com/DataDog/datadog-for-intellij-platform/discussions/14

**Comment by abrooksv** [comment]
We have released our first public beta with PyCharm support to the JetBrains marketplace, please let us know if you find any issues with it.

**Comment by abrooksv** [comment]
Closing this since our Pycharm support is done, please open an issue if you encounter any bugs
