### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by ricmano** [DataDog/datadog-for-intellij-platform#17]
## Is your feature request related to a problem? Please describe.
We have our own sso that is not accessed by normal datadog login page, this means that I'm not able to use the plugin.

## Describe the solution you'd like
We should be able to setup an optional login page

## Describe alternatives you've considered
Use API tokens

**Comment by abrooksv** [comment]
Hi @ricmano 

 Do you use a custom subdomain to access Datadog such as `foobar.datadoghq.com`?
Are you able to use the `Using with Single Sign On?` link on the login page to login through email?

**Comment by ricmano** [comment]
I've just checked that option, you're right, I'll close the issue

**Comment by abrooksv** [comment]
Cool, I am glad you got it working.

Let us know if you have any other issues.

**Comment by ricmano** [comment]
I tried to make it work but our sso is not under a datadog subdomain, I'll create a new issue with a better description
