### ISSUE TITLE
[FEATURE] SSO not in Datadog Subdomain

### ISSUE THREAD

**Issue by ricmano** [DataDog/datadog-for-intellij-platform#18]
## Is your feature request related to a problem? Please describe.
We have our own sso (not under datadog subdomain), so we cannot use the plugin.

## Describe the solution you'd like
We should be able to set an optional login page

## Describe alternatives you've considered
Use API tokens

## Additional context

**Comment by abrooksv** [comment]
A new single sign on flow has been released that is compatible with the IDEs. 

If you are using your company's email address to login, please also try to use the "Using Single Sign-On?" link that appears in the login page.
