### ISSUE TITLE
[FEATURE] PHPstorm integration

### ISSUE THREAD

**Issue by matthieuwerner** [DataDog/datadog-for-intellij-platform#20]
Is there something bloking PHPStorm integration too ? 

I'm a user of Datadog in a multiple projects, and I can't install this extension on phpstorm :(

Thanks in advance for your response 😇

**Comment by jfree** [comment]
Hi Matthieu, 

We've had several requests for PHPStorm support and we'll be releasing a public beta soon.

Best regards,
David

**Comment by matthieuwerner** [comment]
Cool !

Thank you

**Comment by jfree** [comment]
The latest plugin release (v1.2.0) supports PhpStorm.  We are very interested in any feedback you have.
