### ISSUE TITLE
[BUG] Login button goes to blank page (GoLand 2023.3.1 and Intelij IDEA 2023.3.1)

### ISSUE THREAD

**Issue by 15rsirvin** [DataDog/datadog-for-intellij-platform#21]
## Describe the bug
Clicking the `login` button on the datadog plugin takes me to an empty page and the `Logging in...` prompt in the IDE never resolves. 

## Steps To Reproduce
1.) select the datadog plugin
2.) Click `login` button from plugin

<img width="1512" alt="login-failure" src="https://github.com/DataDog/datadog-for-intellij-platform/assets/27705378/185983db-8d55-409b-af9d-bc4d624c9e60">
<img width="336" alt="login-hanging" src="https://github.com/DataDog/datadog-for-intellij-platform/assets/27705378/058bffd7-e4ce-4211-abd5-db250e6a474f">

### Expected Behavior
Going to datadog page to authorize plugin as described in docs.

## Additional Context
- Organization uses `Sign In With Google` to connect to datadog

- URL on request: `https://app.datadoghq.com//oauth2/v1/authorize?client_id=2a900828-7ca9-11ed-993e-da7ad0900002&redirect_uri=http%3A%2F%2F127.0.0.1%3A63342%2Fapi%2Fdatadog%2Foauth%2Fauthorization_code&code_challenge=KWGfRazovBUYLqKVnWXlaIC3dP3AjXhqgB4UQ38VhIU&code_challenge_method=S256&response_type=code&scope=appsec_vm_library_read%20apm_read%20apm_service_catalog_read%20continuous_profiler_read%20first_party_access%20ci_visibility_read%20watchdog_insights_read`

- Was able to successfully login on the Visual Studio Code plugin v1.4.1

## What versions of software are you using?
- Operating System: mac OS ventura 13.6.3
- IDE version: IntelliJ IDEA Ultimate 2023.3.1 (arm64) and GoLand 2023.3.1 (arm64)
- Datadog plugin version v1.1.2
- Browser: Chrome Version 120.0.6099.71 (Official Build) (arm64)

**Comment by 15rsirvin** [comment]
Was able to login by clearing my chrome cookies for datadog and trying again. Not sure why the visual studio code version of the plugin didn't require that step, so still might be worth looking at, but feel free to close.

**Comment by jfree** [comment]
I'm glad you were able to resolve this.  There are some internal differences in the login process between the JetBrains plugin (which uses an external browser) and the VS Code extension (which uses a browser internal to VS Code), so this can result in different behaviors sometimes.

**Comment by abrooksv** [comment]
Root cause discussed in #23
