### ISSUE TITLE
[BUG] Double slash in URL while trying to login

### ISSUE THREAD

**Issue by JorgeCruisebound** [DataDog/datadog-for-intellij-platform#23]
## Describe the bug
When trying to log in, the plug in redirects to an invalid URL:
https://app.datadoghq.com//oauth2/v1/authorize?client_id=...
As you can see, there is a double slash after ".com"

## Steps To Reproduce
There are two ways to reproduce:

**First way**
1. Install the plug in
2. Click on the pop up window to "Login with Datadog"
3. The plug in will open the web browser with the link

**Second way**
1. Install the plug in
2. Go to IntelliJ IDEA -> Settings -> Tools -> Datadog
3. Click on the "+" symbol
4. Click on "Login with Datadog"
5. The plug in will open the web browser with the link
6. See error

![Screenshot 2023-12-28 at 11 44 02 a m](https://github.com/DataDog/datadog-for-intellij-platform/assets/127120563/770dd941-45a6-4bee-b645-7e4fb1d62140)

### Expected Behavior
To be able to login

## Additional Context
After removing the double slash I was able to successfully login, I was trying to reproduce the error again but it seems that after the first attempt it is not reproducible anymore

## What versions of software are you using?
- Operating System: macOS Sonoma 14.2
- Chip: Apple M2 Pro
- IDE version: IntelliJ IDEA 2023.3 (Ultimate Edition)
- Datadog plugin version: 1.2.0

**Comment by jfree** [comment]
Thanks for the report.  I'm not (yet) able to reproduce this.  Which browser do you use?

**Comment by JorgeCruisebound** [comment]
I'm using Chrome Version 120.0.6099.109 (Official Build) (arm64)

**Comment by jfree** [comment]
Thanks. I have the same here. Do you have a single organisation in your Datadog setup, or multiple orgs?  I get to the org selector first, because my user has access to multiple (internal) orgs at Datadog.  I'll see if I can get a setup where there is just one, to see if that path behaves differently.

**Comment by desmond27** [comment]
I am facing this same issue as well. I had to manually remove the slash to get the OAuth app page to load.

**Comment by JorgeCruisebound** [comment]
Sorry for the late response @jfree , I'm in a single organization

**Comment by abrooksv** [comment]
Looks like we may have got bit by a change in behavior in IntelliJ 2023.3
https://github.com/JetBrains/intellij-community/commit/836025bc355c8f0f6db6d045deee9d7c565cf933

**Comment by abrooksv** [comment]
I was able to find the root cause of the issue. It is caused by a change in behavior in IntelliJ 2023.3 (https://github.com/JetBrains/intellij-community/commit/836025bc355c8f0f6db6d045deee9d7c565cf933).

**Comment by abrooksv** [comment]
Bug fix is released on [GitHub](https://github.com/DataDog/datadog-for-intellij-platform/releases/tag/v1.2.1), but pending Jetbrains approval for release on the IDE marketplace

**Comment by abrooksv** [comment]
JetBrains has approved the release and you can now update through your IDEs to 1.2.1. 

Thank you for the bug report, let us know if you are still having issues
