### ISSUE TITLE
[BUG] Python If Return No Else

### ISSUE THREAD

**Issue by JensAstrup** [DataDog/datadog-for-intellij-platform#26]
## Describe the bug
When an `if/elif` statement is used and the `if` has a return, the plugin erroneously states that the else is not necessary because `if` has a return, when it should be recognizing that `elif` is being used which states a condition and not `else`. 

## Steps To Reproduce
1. Write some Python with an `if/elif` block, ensure that the `if` statement has a `return`

![Screenshot 2024-01-30 at 7 30 43 PM](https://github.com/DataDog/datadog-for-intellij-platform/assets/11978008/37dee991-c775-4d25-be36-3c8fe3634a65)
![Screenshot 2024-01-30 at 7 30 56 PM](https://github.com/DataDog/datadog-for-intellij-platform/assets/11978008/a52b2eae-cefe-44c6-a6d1-e3be65868c08)

### Expected Behavior
There should be no warning on `if/elif` blocks for the `if no return else` check

## What versions of software are you using?
- Operating System: Ventura 13.6.4
- IDE version: PyCharm 2023.3.3 (Professional Edition)
- Datadog plugin version: 1.2.2

**Comment by juli1** [comment]
@JensAstrup thank you for your report. Can you please check again - the bug should be fixed.

**Comment by JensAstrup** [comment]
Yep, it looks fixed, thanks! :)
