### ISSUE TITLE
[FEATURE] Static Analysis Inspection Profile Setting

### ISSUE THREAD

**Issue by JensAstrup** [DataDog/datadog-for-intellij-platform#27]
## Is your feature request related to a problem? Please describe.
There are a handful of inspections I would like to disable - I want Python's best practices warnings, but there a couple I don't care to see warnings about. My only option though is to disable Datadog's static analysis entirely, I can't supress individual warnings. 

## Describe the solution you'd like
Inspections should be listed individually so that they can be disabled or have custom severity levels

## Additional context
![Screenshot 2024-01-30 at 7 39 19 PM](https://github.com/DataDog/datadog-for-intellij-platform/assets/11978008/a60828ad-d318-4fd4-a0b0-8c23478c8d40)
![Screenshot 2024-01-30 at 7 39 46 PM](https://github.com/DataDog/datadog-for-intellij-platform/assets/11978008/c56641e9-e3f0-49d0-bb30-d5f405484658)

**Comment by juli1** [comment]
@JensAstrup thanks for the feedback! 

For now, you can either
1. Remove the `python-best-practices` from your `static-analysis.datadog.yml` file
2. Remove the occurences by putting `no-dd-sa` in the line above the issue

We are planning to have a quick fix to ignore rulesets in the coming weeks/months.

Out of curiosity, can you also tell us what rules are noisy and if we could improve them?

Thank you,

**Comment by JensAstrup** [comment]
Not necessarily noisy in a way that you'd have to remove them, just specific to the project I happen to be in. 

Convention calls for defining `User` at top-level using the Django method `get_user_model` and treating the variable name as if it were the User class itself, which static analysis rightly doesn't like:
![Screenshot 2024-01-30 at 8 46 18 PM](https://github.com/DataDog/datadog-for-intellij-platform/assets/11978008/c85010b9-83d5-4401-9474-561dd2fa49b0)

I would use `no-dd-sa`, but not everyone on the team is using the plugin so don't want to add in to their view. Also just personally never feels right having stuff in the code to make IDEs change behavior 🤷

**Comment by juli1** [comment]
> Not necessarily noisy in a way that you'd have to remove them, just specific to the project I happen to be in.
> 
> Convention calls for defining `User` at top-level using the Django method `get_user_model` and treating the variable name as if it were the User class itself, which static analysis rightly doesn't like: ![Screenshot 2024-01-30 at 8 46 18 PM](https://private-user-images.githubusercontent.com/11978008/301026522-c85010b9-83d5-4401-9474-561dd2fa49b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDIwNjIsIm5iZiI6MTcwNjcwMTc2MiwicGF0aCI6Ii8xMTk3ODAwOC8zMDEwMjY1MjItYzg1MDEwYjktODNkNS00NDAxLTk0NzQtNTYxZGQyZmE0OWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDExNDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MTBiNWYzNjJiNTQzYmY0NGEwNzAxZTA1MjMxM2I4MTFlMWE4MjhjYjU2MWJjNTFiMTIxODkyZDk1MDgyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_ZM89-pWDfxuzRdHUccNVWJ5Gbshd9MRahU3mUfzik)

This is actually really good feedback. We should probably shut down this rule as this is way too noisy and trigger some false positives for models.

> I would use `no-dd-sa`, but not everyone on the team is using the plugin so don't want to add in to their view. Also just personally never feels right having stuff in the code to make IDEs change behavior 🤷

Thank you for your feedback. Some users want the `no-dd-sa` but it does not solve all issues and we need to do better and we will have the ability to add/remove a rulesets or rule for the whole project soon.

**Comment by juli1** [comment]
Also, FYI, we disabled this rule for now until we have better mechanisms to enable/disable rules/rulesets.

**Comment by jfree** [comment]
The latest plugin release (v1.4.1) enables individual Static Analysis rules to be suppressed project-wide.  From the context menu, select `Suppress violations of this rule for the whole project` and the config file will be updated accordingly:
 
![image](https://github.com/DataDog/datadog-for-intellij-platform/assets/1835893/9d0ace36-fb42-49f6-b39b-e281d66a1be0)

I'll close this ticket but don't hesitate to open a new ticket if you have additional feedback.  Thanks for helping to improve the Datadog plugin!
